# Generated by Django 5.2.16 on 2026-08-01 06:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=300)),
                ('publication', models.CharField(blank=True, max_length=200)),
                ('published_year', models.PositiveSmallIntegerField(blank=True, db_index=True, null=True)),
                ('reading_minutes', models.PositiveSmallIntegerField(default=0)),
                ('blurb', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('is_seed', models.BooleanField(default=False)),
            ],
            options={
                'indexes': [models.Index(fields=['is_published', '-published_year'], name='shelf_essay_is_publ_a2bf8f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handle', models.SlugField(max_length=40, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('bio', models.CharField(blank=True, max_length=280)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=160)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('is_public', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Shelving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('removed_at', models.DateTimeField(blank=True, null=True)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelvings', to='shelf.essay')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelvings', to='shelf.shelf')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shelvings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.TextField(max_length=2000)),
                ('is_hidden', models.BooleanField(default=False)),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='shelf.essay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['essay', '-created_at'], name='shelf_note_essay_i_8558ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('half_stars', models.PositiveSmallIntegerField(help_text='1..10, where 10 is five stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('essay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='shelf.essay')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['essay', 'half_stars'], name='shelf_ratin_essay_i_680080_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'essay'), name='uniq_rating_per_user_essay'), models.CheckConstraint(condition=models.Q(('half_stars__gte', 1), ('half_stars__lte', 10)), name='half_stars_in_range')],
            },
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='uniq_shelf_slug_per_owner'),
        ),
        migrations.AddConstraint(
            model_name='shelf',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('owner',), name='one_default_shelf_per_owner'),
        ),
        migrations.AddIndex(
            model_name='shelving',
            index=models.Index(fields=['essay', '-created_at'], name='shelf_shelv_essay_i_a32ace_idx'),
        ),
        migrations.AddIndex(
            model_name='shelving',
            index=models.Index(fields=['user', '-created_at'], name='shelf_shelv_user_id_6f904c_idx'),
        ),
        migrations.AddConstraint(
            model_name='shelving',
            constraint=models.UniqueConstraint(fields=('user', 'essay', 'shelf'), name='uniq_shelving'),
        ),
    ]
