# Generated by Django 5.2.16 on 2026-08-05 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_submissions(apps, schema_editor):
    Essay = apps.get_model("shelf", "Essay")
    Shelving = apps.get_model("shelf", "Shelving")
    for essay in Essay.objects.filter(is_seed=False, submitted_by__isnull=True).iterator():
        submitter_id = (
            Shelving.objects.filter(essay_id=essay.pk)
            .order_by("created_at", "pk")
            .values_list("user_id", flat=True)
            .first()
        )
        if submitter_id:
            Essay.objects.filter(pk=essay.pk).update(submitted_by_id=submitter_id)


def unlink_submissions(apps, schema_editor):
    apps.get_model("shelf", "Essay").objects.update(submitted_by=None)


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_essays', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(link_existing_submissions, unlink_submissions),
    ]
